server:
  port: 8083

spring:
  application:
    name: ms-load-allocation

  datasource:
    url: jdbc:postgresql://localhost:5432/truckdar_db
    username: truckdar_admin
    password: truckdar_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer